src/SimpleBlog/Pages/Admin.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using SimpleBlog.Model;
using SimpleBlog.Services;
using SimpleBlog.ViewModels;

namespace SimpleBlog.Pages
{
    [Authorize]
    public class AdminModel : Microsoft.AspNetCore.Mvc.RazorPages.PageModel
    {
        private readonly IArticlesService _articlesService;

        public List<ArticleViewModel> Articles { get; set; }

        public AdminModel(IArticlesService articlesService)
        {
            _articlesService = articlesService;
        }

        public async Task OnGet()
        {
            var articleInfos = (await _articlesService.GetAllArticleInfosAsync()).ToDictionary(a => a.ArticleId, a => a);
            Articles = (await _articlesService.GetAllAsync()).Select(a => MapToViewModel(a, articleInfos.ContainsKey(a.Id) ? articleInfos[a.Id] : null)).ToList();
        }

        public async Task<IActionResult> OnPostDeleteArticleAsync(string id)
        {
            await _articlesService.DeteleAsync(id);
            return RedirectToPage("/admin");
        }

        private static ArticleViewModel MapToViewModel(Article article, ArticleInfo articleInfo)
        {
            return new ArticleViewModel
            {
                Id = article.Id,
                Title = article.Title,
                Created = article.Created,
                Published = article.Published,
                ViewsCount = articleInfo != null ? articleInfo.ViewsCount : 0,
                CommentsCount = articleInfo != null ? articleInfo.CommentsCount : 0
            };
        }
    }
}

src/SimpleBlog/Pages/AdminArticle.cshtml.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Diagnostics;
using System.IO;
using System.Linq;
using System.Reflection;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using SimpleBlog.Model;
using SimpleBlog.Repositories;
using SimpleBlog.Services;

namespace SimpleBlog.Pages
{
    [Authorize]
    public class AdminArticleModel : Microsoft.AspNetCore.Mvc.RazorPages.PageModel
    {
        private readonly IArticlesService _articlesService;
        private readonly IImagesRepository _imagesRepository;

        [BindProperty]
        [Required]
        [Display(Name = "URL name")]
        public string ArticleId { get; set; }

        [BindProperty]
        [Required]
        [Display(Name = "Title")]
        public string Title { get; set; }

        [BindProperty]
        [Required]
        [Display(Name = "Body")]
        public string Body { get; set; }

        [BindProperty]
        [Required]
        [Display(Name = "Tags (comma separated)")]
        public string Tags { get; set; }

        [BindProperty]
        [Required]
        [Display(Name = "Published")]
        public bool Published { get; set; }

        public List<string> Images { get; set; }

        [BindProperty]
        public List<IFormFile> UploadImages { get; set; }

        public AdminArticleModel(IArticlesService articlesService, IImagesRepository imagesRepository)
        {
            _articlesService = articlesService;
            _imagesRepository = imagesRepository;
        }

        public async Task OnGet(string id)
        {
            if (string.IsNullOrEmpty(id))
            {
                Published = true;
                Images = new List<string>();
                return;
            }

            var article = await _articlesService.GetAsync(id);

            Images = (await _imagesRepository.GetAllAsync(id)).Select(i => Path.GetFileName(i)).ToList();

            MapFromArticle(article);
        }

        public async Task<IActionResult> OnPostDeleteImageAsync(string id, string fileName)
        {
            await _imagesRepository.DeleteAsync(id, fileName);
            return RedirectToPage("/adminarticle", new { id });
        }

        public async Task<IActionResult> OnPostImageAsync(string id)
        {
            foreach (var image in UploadImages)
            {
                await _imagesRepository.UploadAsync(id, image);
            }
            return RedirectToPage("/adminarticle", new { id });
        }

        public async Task<IActionResult> OnPostDataAsync(string id)
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            var article = MapToArticle();

            if (string.IsNullOrEmpty(id))
            {
                await _articlesService.CreateAsync(article);
            } else
            {
                await _articlesService.UpdateAsync(article);
            }

            return RedirectToPage("/admin");
        }

        private Article MapToArticle()
        {
            return new Article
            {
                Id = ArticleId,
                Title = Title,
                Body = Body,
                Tags = new List<string>(Tags.Split(',').Select(t => t.Trim())),
                Published = Published
            };
        }
        private void MapFromArticle(Article article)
        {
            ArticleId = article.Id;
            Title = article.Title;
            Body = article.Body;
            Tags = string.Join(", ", article.Tags);
            Published = article.Published;
        }
    }
}

src/SimpleBlog/Pages/AdminComments.cshtml.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using SimpleBlog.Model;
using SimpleBlog.Services;
using System;
using System.Collections.Generic;
using System.Threading.Tasks;

namespace SimpleBlog.Pages
{
    [Authorize]
    public class AdminCommentsModel : Microsoft.AspNetCore.Mvc.RazorPages.PageModel
    {
        private readonly IArticlesService _articlesService;
        public List<Comment> Comments { get; set; }

        public AdminCommentsModel(IArticlesService articlesService)
        {
            _articlesService = articlesService;
        }

        public async Task OnGet()
        {
            Comments = await _articlesService.GetUnreadedCommentsAsync();
        }

        public async Task<IActionResult> OnPostDeleteAsync(Guid id)
        {
            await _articlesService.DeleteCommentAsync(id);
            return RedirectToPage("/admincomments");
        }
        public async Task<IActionResult> OnPostMarkAsReadAsync(Guid id)
        {
            await _articlesService.MarkCommentAsReadAsync(id);
            return RedirectToPage("/admincomments");
        }
    }
}

src/SimpleBlog/Pages/AdminConfig.cshtml.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using SimpleBlog.Model;
using SimpleBlog.Repositories;

namespace SimpleBlog.Pages
{
    [Authorize]
    public class AdminConfigModel : Microsoft.AspNetCore.Mvc.RazorPages.PageModel
    {
        private const string AppInsightsConnectionStringEnvironmentVariableName = "APPLICATIONINSIGHTS_CONNECTION_STRING";

        private readonly ISiteConfigurationRepository _configRepository;
        private readonly IImagesRepository _imagesRepository;

        [BindProperty]
        [Required]
        [Display(Name = "Title")]
        public string Title { get; set; }

        [BindProperty]
        [Required]
        [Display(Name = "Owner")]
        public string Owner { get; set; }

        [BindProperty]
        [Required]
        [Display(Name = "How many posts on one page")]
        public int BlogPostsPageSize { get; set; }

        [BindProperty]
        [Required]
        [Display(Name = "How many latest and popular posts on index page")]
        public int LatestBlogPostsCount { get; set; }

        [BindProperty]
        [Required]
        [Display(Name = "Enable client-side telemetry")]
        public bool EnableClientSideTelemetry { get; set; }
        public bool InstrumentationKeyProvided => !string.IsNullOrEmpty(Environment.GetEnvironmentVariable(AppInsightsConnectionStringEnvironmentVariableName));

        [BindProperty]
        [Required]
        [Display(Name = "How many recommended articles to show for each article")]
        public int RecommendedArticlesCount { get; set; }

        [BindProperty]
        [Required]
        [Display(Name = "Enable comments for articles")]
        public bool EnableComments{ get; set; }

        public List<MenuItem> MenuItems { get; set; }

        public bool FaviconExists { get;  private set; }

        [BindProperty]
        public List<IFormFile> UploadFavicons { get; set; }


        public AdminConfigModel(ISiteConfigurationRepository configRepository, IImagesRepository imagesRepository)
        {
            _configRepository = configRepository;
            _imagesRepository = imagesRepository;
        }

        public async Task OnGet()
        {
            var config = await _configRepository.GetAsync();
            MapFromSiteConfiguration(config);

            MenuItems = await _configRepository.GetAllMenuItemsAsync();

            FaviconExists = await _imagesRepository.FaviconExists();
        }

        public async Task<IActionResult> OnPostDeleteMenuItemAsync(string title)
        {
            await _configRepository.DeleteAsync(title);
            return RedirectToPage("/adminconfig");
        }

        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid)
            {
                MenuItems = await _configRepository.GetAllMenuItemsAsync();
                FaviconExists = await _imagesRepository.FaviconExists();
                return Page();
            }

            var config = MapToSiteConfiguration();

            await _configRepository.UpdateAsync(config);

            return RedirectToPage("/adminconfig");
        }

        public async Task<IActionResult> OnPostFaviconAsync(string id)
        {
            foreach (var image in UploadFavicons)
            {
                await _imagesRepository.UploadFaviconAsync(image);
            }
            return RedirectToPage("/adminconfig", new { id });
        }

        private SiteConfiguration MapToSiteConfiguration()
        {
            return new SiteConfiguration
            {
                Title = Title,
                Owner = Owner,
                BlogPostsPageSize = BlogPostsPageSize,
                LatestBlogPostsCount = LatestBlogPostsCount,
                EnableClientSideTelemetry = EnableClientSideTelemetry,
                RecommendedArticlesCount = RecommendedArticlesCount,
                EnableComments = EnableComments
            };
        }

        private void MapFromSiteConfiguration(SiteConfiguration config)
        {
            Title = config.Title;
            Owner = config.Owner;
            BlogPostsPageSize = config.BlogPostsPageSize;
            LatestBlogPostsCount = config.LatestBlogPostsCount;
            EnableClientSideTelemetry = config.EnableClientSideTelemetry;
            RecommendedArticlesCount = config.RecommendedArticlesCount;
            EnableComments = config.EnableComments;
        }
    }
}

src/SimpleBlog/Pages/AdminMenu.cshtml.cs
using System.ComponentModel.DataAnnotations;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using SimpleBlog.Model;
using SimpleBlog.Repositories;

namespace SimpleBlog.Pages
{
    [Authorize]
    public class AdminMenuModel : Microsoft.AspNetCore.Mvc.RazorPages.PageModel
    {
        private readonly ISiteConfigurationRepository _configRepository;

        [BindProperty]
        [Required]
        [Display(Name = "Order")]
        public int Order { get; set; }

        [BindProperty]
        [Required]
        [Display(Name = "Title")]
        public string MenuTitle { get; set; }

        [BindProperty]
        [Required]
        [Display(Name = "Url")]
        public string MenuUrl { get; set; }

        public AdminMenuModel(ISiteConfigurationRepository configRepository)
        {
            _configRepository = configRepository;
        }

        public async Task OnGet(string title)
        {
            if (string.IsNullOrEmpty(title))
            {
                return;
            }

            var menuItem = await _configRepository.GetMenuItemAsync(title);
            MapFromMenuItem(menuItem);
        }

        public async Task<IActionResult> OnPost(string title)
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            var menuItem = MapToMenuItem();

            if (string.IsNullOrEmpty(title))
            {
                await _configRepository.CreateMenuItemAsync(menuItem);
            }
            else
            {
                await _configRepository.UpdateMenuItemAsync(title, menuItem);
            }

            return RedirectToPage("/adminconfig");
        }

        private MenuItem MapToMenuItem()
        {
            return new MenuItem
            {
                Order = Order,
                Title = MenuTitle,
                Url = MenuUrl
            };
        }

        private void MapFromMenuItem(MenuItem menuItem)
        {
            Order = menuItem.Order;
            MenuTitle = menuItem.Title;
            MenuUrl = menuItem.Url;
        }
    }
}

src/SimpleBlog/Pages/AdminPage.cshtml.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using SimpleBlog.Model;
using SimpleBlog.Repositories;
using SimpleBlog.Services;

namespace SimpleBlog.Pages
{
    [Authorize]
    public class AdminPageModel : Microsoft.AspNetCore.Mvc.RazorPages.PageModel
    {
        private readonly IPagesService _pagesService;
        private readonly IImagesRepository _imagesRepository;

        [BindProperty]
        [Required]
        [Display(Name = "URL name")]
        public string PageId { get; set; }

        [BindProperty]
        [Required]
        [Display(Name = "Title")]
        public string Title { get; set; }

        [BindProperty]
        [Required]
        [Display(Name = "Body")]
        public string Body { get; set; }

        public List<string> Images { get; set; }

        [BindProperty]
        public List<IFormFile> UploadImages { get; set; }

        public AdminPageModel(IPagesService pagesService, IImagesRepository imagesRepository)
        {
            _pagesService = pagesService;
            _imagesRepository = imagesRepository;
        }

        public async Task OnGet(string id)
        {
            if (string.IsNullOrEmpty(id))
            {
                Images = new List<string>();
                return;
            }

            var page = await _pagesService.GetAsync(id);
            MapFromPage(page);

            Images = (await _imagesRepository.GetAllAsync(id)).Select(i => Path.GetFileName(i)).ToList();
        }

        public async Task<IActionResult> OnPostImageAsync(string id)
        {
            foreach (var image in UploadImages)
            {
                await _imagesRepository.UploadAsync(id, image);
            }
            return RedirectToPage("/adminpage", new { id });
        }

        public async Task<IActionResult> OnPostDeleteImageAsync(string id, string fileName)
        {
            await _imagesRepository.DeleteAsync(id, fileName);
            return RedirectToPage("/adminpage", new { id });
        }

        public async Task<IActionResult> OnPostDataAsync(string id)
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            var page = MapToPage();

            if (string.IsNullOrEmpty(id))
            {
                await _pagesService.CreateAsync(page);
            }
            else
            {
                await _pagesService.UpdateAsync(page);
            }

            return RedirectToPage("/adminpages");
        }

        private Page MapToPage()
        {
            return new Page
            {
                Id = PageId,
                Title = Title,
                Body = Body
            };
        }
        private void MapFromPage(Page page)
        {
            PageId = page.Id;
            Title = page.Title;
            Body = page.Body;
        }
    }
}

src/SimpleBlog/Pages/AdminPages.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using SimpleBlog.Model;
using SimpleBlog.Services;

namespace SimpleBlog.Pages
{
    [Authorize]
    public class AdminPagesModel : Microsoft.AspNetCore.Mvc.RazorPages.PageModel
    {
        private readonly IPagesService _pagesService;
        public List<Page> Pages { get; set; }

        public AdminPagesModel(IPagesService pagesService)
        {
            _pagesService = pagesService;
        }

        public async Task OnGet()
        {
            Pages = await _pagesService.GetAllAsync();
        }

        public async Task<IActionResult> OnPostDeletePage(string id)
        {
            await _pagesService.DeleteAsync(id);
            return RedirectToPage("/adminpages");
        }
    }
}

src/SimpleBlog/Pages/Admin.cshtml
@page "/admin"
@model SimpleBlog.Pages.AdminModel
@{
    Layout = "_AdminLayout";
    ViewData["Title"] = "Admin";
}

<div class="page-title-small">
    <div class="container">
        <h1>Posts</h1>
    </div>
</div>

<div class="container page-body">
    <a class="btn btn-primary" role="button" asp-page="/adminarticle">Add post</a>
    <form method="post">
        <table class="table mt-3">
            <thead class="thead-light">
                <tr>
                    <th scope="col">URL</th>
                    <th scope="col">Title</th>
                    <th scope="col">Created</th>
                    <th scope="col">Published</th>
                    <th scope="col">Views</th>
                    <th scope="col">Comments</th>
                    <th scope="col">Actions</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var article in Model.Articles)
                {
                    <tr>
                        <td><a asp-page="/blogarticle" asp-route-id="@article.Id">@article.Id</a></td>
                        <td><a asp-page="/adminarticle" asp-route-id="@article.Id">@article.Title</a></td>
                        <td>@article.Created</td>
                        <td>@article.Published</td>
                        <td>@article.ViewsCount</td>
                        <td>@article.CommentsCount</td>
                        <td><button type="submit" class="btn btn-link button-link-with-links" asp-page-handler="DeleteArticle" asp-route-id="@article.Id">Delete</button></td>
                    </tr>
                }
            </tbody>
        </table>
    </form>
</div>

src/SimpleBlog/Pages/AdminArticle.cshtml
@page "/admin/article/{id?}"
@model SimpleBlog.Pages.AdminArticleModel
@{
    Layout = "_AdminLayout";
    ViewData["Title"] = "Admin Article";
}

@section Scripts {
    <script src="~/js/site.js"></script>
}

<div class="page-title-small">
    <div class="container">
        <h1>Add new post</h1>
    </div>
</div>

<div class="container page-body">
    <p>
        <a asp-page="/admin">Back to Posts</a>
    </p>
    <h3>Images</h3>
    <form method="post">
        <table class="table mt-3">
            <thead class="thead-light">
                <tr>
                    <th scope="col">File name</th>
                    <th scope="col">Actions</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var file in Model.Images)
                {
                    <tr>
                        <td><a href="/blogimages/@Model.ArticleId/@file" target="_blank" rel="noopener noreferrer">@file</a></td>
                        <td>
                            <ul class="list-inline">
                                <li class="list-inline-item"><a href="javascript:addImageReferenceToTextArea('Body','@Model.ArticleId','@System.IO.Path.GetFileNameWithoutExtension(file)','@file')">Add reference to markdown</a></li>
                                <li class="list-inline-item">|</li>
                                <li class="list-inline-item"><button type="submit" class="btn btn-link button-link-with-links" asp-page-handler="DeleteImage" asp-route-fileName="@file">Delete</button></li>
                            </ul>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </form>
    <form method="post" enctype="multipart/form-data">
        <div class="mb-3">
            <input class="form-control py-1" type="file" asp-for="UploadImages" multiple />
        </div>
        <button type="submit" class="btn btn-primary" asp-page-handler="Image">Upload image</button>
    </form>
    <h3 class="mt-4">Post</h3>
    <form method="post">
        <div class="form-group">
            @Html.LabelFor(m => m.ArticleId)
            @if (string.IsNullOrEmpty(Model.ArticleId))
            {
                @Html.TextBoxFor(m => m.ArticleId, new { @class = "form-control" })
                @Html.ValidationMessageFor(m => m.ArticleId, "", new { @class = "text-danger" })
            }
            else
            {
                @Html.TextBoxFor(m => m.ArticleId, new { @class = "form-control", @readonly = "readonly" })
            }
        </div>
        <div class="form-group">
			@if (string.IsNullOrEmpty(Model.ArticleId))
            {
                @Html.LabelFor(m => m.Title)
				<div class="row">
                    <div class="col-11">@Html.TextBoxFor(m => m.Title, new { @class = "form-control" })</div>
                    <div class="col mt-2"><a href="javascript:titleToUrl('Title','ArticleId')">To URL</a></div>
				</div>
                @Html.ValidationMessageFor(m => m.Title, "", new { @class = "text-danger" })
            } else {
                @Html.LabelFor(m => m.Title)
                @Html.TextBoxFor(m => m.Title, new { @class = "form-control" })
                @Html.ValidationMessageFor(m => m.Title, "", new { @class = "text-danger" })
			}
        </div>
        <div class="form-group">
            @Html.LabelFor(m => m.Body)
            @Html.TextAreaFor(m => m.Body, 30, 0, new { @class = "form-control" })
            @Html.ValidationMessageFor(m => m.Body, "", new { @class = "text-danger" })
        </div>
        <div class="form-group">
            @Html.LabelFor(m => m.Tags)
            @Html.TextBoxFor(m => m.Tags, new { @class = "form-control" })
            @Html.ValidationMessageFor(m => m.Tags, "", new { @class = "text-danger" })
        </div>
        <div class="form-group form-check">
            @Html.CheckBoxFor(m => m.Published, new { @class = "form-check-input" })
            @Html.LabelFor(m => m.Published, new { @class = "form-check-label" })
        </div>
        <button type="submit" class="btn btn-primary" asp-page-handler="Data">Save</button>
    </form>
</div>

src/SimpleBlog/Pages/AdminComments.cshtml
@page "/admin/comments"
@model SimpleBlog.Pages.AdminCommentsModel
@{
    Layout = "_AdminLayout";
    ViewData["Title"] = "Admin Comments";
}

<div class="page-title-small">
    <div class="container">
        <h1>Unreaded comments</h1>
    </div>
</div>

<div class="container page-body">
    @if (Model.Comments.Count == 0)
    {
      <p>All comments read</p>
    } else {
    <form method="post">
        <table class="table mt-3">
            <thead class="thead-light">
                <tr>
                    <th scope="col">Page</th>
                    <th scope="col">Comment</th>
                    <th scope="col">Actions</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var comment in Model.Comments)
                {
                    <tr>
                        <td><a asp-page="/blogarticle" asp-route-id="@comment.ArticleId">@comment.ArticleId</a></td>
                        <td>
                            <div class="row">
                                <div class="col">
                                    <p><b>@comment.Author</b></p>
                                </div>
                                <div class="col text-right">
                                    <p>@comment.Created.ToString("MMMM dd, yyyy")</p>
                                </div>
                            </div>
                            <p class="comment">@comment.Content</p>
                        </td>
                        <td>
                            <ul class="list-inline">
                                <li class="list-inline-item"><button type="submit" class="btn btn-link button-link-with-links" asp-page-handler="MarkAsRead" asp-route-id="@comment.Id">Mark as read</button></li>
                                <li class="list-inline-item"><button type="submit" class="btn btn-link button-link-with-links" asp-page-handler="Delete" asp-route-id="@comment.Id">Delete</button></li>
                            </ul>
                    </tr>
                }
            </tbody>
        </table>
    </form>
    }
</div>

src/SimpleBlog/Pages/AdminMenu.cshtml
@page "admin/config/menuitem/{title?}"
@model SimpleBlog.Pages.AdminMenuModel
@{
    Layout = "_AdminLayout";
    ViewData["Title"] = "Admin Menu Item";
}

<div class="page-title-small">
    <div class="container">
        <h1>Add new menu item</h1>
    </div>
</div>

<div class="container page-body">
    <p>
        <a asp-page="/adminconfig">Back to Config</a>
    </p>
    <form method="post">
        <div class="form-group">
            @Html.LabelFor(m => m.Order)
            @Html.TextBoxFor(m => m.Order, new { @class = "form-control" })
            @Html.ValidationMessageFor(m => m.Order, "", new { @class = "text-danger" })
        </div>
        <div class="form-group">
            @Html.LabelFor(m => m.MenuTitle)
            @Html.TextBoxFor(m => m.MenuTitle, new { @class = "form-control" })
            @Html.ValidationMessageFor(m => m.MenuTitle, "", new { @class = "text-danger" })
        </div>
        <div class="form-group">
            @Html.LabelFor(m => m.MenuUrl)
            @Html.TextBoxFor(m => m.MenuUrl, new { @class = "form-control" })
            @Html.ValidationMessageFor(m => m.MenuUrl, "", new { @class = "text-danger" })
        </div>
        <button type="submit" class="btn btn-primary">Save</button>
    </form>
</div>

src/SimpleBlog/Pages/AdminPage.cshtml
@page "/admin/page/{id?}"
@model SimpleBlog.Pages.AdminPageModel
@{
    Layout = "_AdminLayout";
    ViewData["Title"] = "Admin Page";
}

@section Scripts {
    <script src="~/js/site.js"></script>
}

<div class="page-title-small">
    <div class="container">
        <h1>Add new page</h1>
    </div>
</div>

<div class="container page-body">
    <p>
        <a asp-page="/adminpages">Back to Pages</a>
    </p>
    <h3>Images</h3>
    <form method="post">
        <table class="table mt-3">
            <thead class="thead-light">
                <tr>
                    <th scope="col">File name</th>
                    <th scope="col">Actions</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var file in Model.Images)
                {
                    <tr>
                        <td><a href="/blogimages/@Model.PageId/@file" target="_blank" rel="noopener noreferrer">@file</a></td>
                        <td>
                            <ul class="list-inline">
                                <li class="list-inline-item"><a class="mt-1" href="javascript:addImageReferenceToTextArea('Body','@Model.PageId','@System.IO.Path.GetFileNameWithoutExtension(file)','@file')">Add reference to markdown</a></li>
                                <li class="list-inline-item">|</li>
                                <li class="list-inline-item"><button type="submit" class="btn btn-link button-link-with-links" asp-page-handler="DeleteImage" asp-route-fileName="@file">Delete</button></li>
                            </ul>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </form>
    <form method="post" enctype="multipart/form-data">
        <div class="mb-3">
            <input class="form-control py-1" type="file" asp-for="UploadImages" multiple />
        </div>
        <button type="submit" class="btn btn-primary" asp-page-handler="Image">Upload image</button>
    </form>
    <h3 class="mt-3">Page</h3>
    <form method="post">
        <div class="form-group">
            @Html.LabelFor(m => m.PageId)
            @if (string.IsNullOrEmpty(Model.PageId))
            {
                @Html.TextBoxFor(m => m.PageId, new { @class = "form-control" })
                @Html.ValidationMessageFor(m => m.PageId, "", new { @class = "text-danger" })
            }
            else
            {
                @Html.TextBoxFor(m => m.PageId, new { @class = "form-control", @readonly = "readonly" })
            }
        </div>
        <div class="form-group">
            @Html.LabelFor(m => m.Title)
            @Html.TextBoxFor(m => m.Title, new { @class = "form-control" })
            @Html.ValidationMessageFor(m => m.Title, "", new { @class = "text-danger" })
        </div>
        <div class="form-group">
            @Html.LabelFor(m => m.Body)
            @Html.TextAreaFor(m => m.Body, 30, 0, new { @class = "form-control" })
            @Html.ValidationMessageFor(m => m.Body, "", new { @class = "text-danger" })
        </div>
        <button type="submit" class="btn btn-primary" asp-page-handler="Data">Save</button>
    </form>
</div>

src/SimpleBlog/Pages/AdminPages.cshtml
@page "/admin/pages"
@model SimpleBlog.Pages.AdminPagesModel
@{
    Layout = "_AdminLayout";
    ViewData["Title"] = "Admin Pages";
}

<div class="page-title-small">
    <div class="container">
        <h1>Pages</h1>
    </div>
</div>

<div class="container page-body">
    <a class="btn btn-primary" role="button" asp-page="/adminpage">Add page</a>
    <form method="post">
        <table class="table mt-3">
            <thead class="thead-light">
                <tr>
                    <th scope="col">URL</th>
                    <th scope="col">Title</th>
                    <th scope="col">Actions</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var pageItem in Model.Pages)
                {
                    <tr>
                        <td><a asp-page="/page" asp-route-id="@pageItem.Id">@pageItem.Id</a></td>
                        <td><a asp-page="/adminpage" asp-route-id="@pageItem.Id">@pageItem.Title</a></td>
                        <td><button type="submit" class="btn btn-link button-link-with-links" asp-page-handler="DeletePage" asp-route-id="@pageItem.Id">Delete</button></td>
                    </tr>
                }
            </tbody>
        </table>
    </form>
</div>